predefined_responses = {
    "Hello": "Hello! How can I assist you today?",
    "What is your name?": "I am a simple chatbot created to assist you.",
    "How are you?": "I'm doing well! Thanks for asking. How can I assist you today?",
    "Bye": "Goodbye! Have a great day!",
    "Help": "I'm here to help! What kind of assistance do you need?",
    "Thank you": "You're welcome! Is there anything else I can help you with?",
    "Weather": "I'm sorry, I don't have real-time weather information. You might want to check a weather website or app for that.",
    "Tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "What time is it?": "I'm sorry, I don't have access to real-time information. You can check the time on your device.",
    "Who created you?": "I was created by Abirami as a simple chatbot to assist users.",
    "What can you do?": "I can answer your questions, provide assistance, and even tell you jokes. Just ask away!",
    "Where are you from?": "I live in the cloud, available whenever you need me.",
    "How old are you?": "I don't age like humans, but I was created quite recently!",
    "Do you have hobbies?": "I enjoy helping people and learning new things from our conversations!",
    "What is AI?": "AI stands for Artificial Intelligence, which is a branch of computer science aimed at creating smart machines that can perform tasks that usually require human intelligence.",
    "Do you sleep?": "I don't need sleep! I'm here 24/7 to assist you.",
    "Are you a human?": "No, I'm not human. I'm a chatbot created to assist you.",
    "What is your favorite color?": "I like all colors equally, but if I had to choose, I'd go with blue. It feels calm and friendly.",
    "What is the meaning of life?": "The meaning of life is a deep philosophical question. Some say it's to be happy and enjoy the moment, while others believe it's to make a difference in the world.",
    "Do you have any pets?": "I'm sorry, I don't have any physical form. But I can help you with your questions!",
    "What is the capital of France?": "The capital of France is Paris.",
    "Can you play music?": "I'm sorry, I don't have the ability to play music. I can help you with your questions though!",
    "What is the speed of light?": "The speed of light is approximately 299,792,458 meters per second in a vacuum.",
    "Do you have any siblings?": "I'm sorry, I don't have any physical form. But I can help you with your questions!",
    "What is the square root of 144?": "The square root of 144 is 12.",
    "Can you tell me a secret?": "I'm sorry, I don't have the ability to store or share secrets. I can help you with your questions though!",
}
